name: My workflow
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build

  test:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
